### ISSUE TITLE
SM4的pad问题

### ISSUE THREAD

**Issue by liyangzbx** [huangbaoliu/sm2_sm3_sm4_tools#3]
如上，以HEX字符输入时，输入恰好为32H，应该不需填充才行。但不选pad，代码中如下部分会报错“'CryptSM4' object has no attribute 'crypt_ecb_nopad'
```
if self.mode == "ECB":
    if len(sm4_plaintext) % 16 != 0:
        self.Qmsgbox_show("Error", "Plaintext len (%d) HEXs is not 16's bytes" % len(sm4_plaintext))
        return
    encrypt_value = crypt_sm4.crypt_ecb_nopad(sm4_plaintext)
```
如果勾选了pad，加密结果就会输出64H。而实际我的场景是加解密都是只能输入32H。此处怎样解决这个pad的问题呢？
我目前是把gmssl.sm4里面pad部分给注释掉了，如下：
```
def crypt_ecb(self, input_data):
    # SM4-ECB block encryption/decryption
    input_data = bytes_to_list(input_data)
    # if self.mode == SM4_ENCRYPT:
    #     input_data = padding(input_data)
```
但是这样移植到别的环境就不好维护了，此处有什么解决方法吗？谢谢。

**Comment by huangbaoliu** [comment]
有crypt_ecb_nopad函数呀，我测试过不会报错呀！是不是你下载的源码有问题？
![image](https://user-images.githubusercontent.com/31270967/114341088-85a6e980-9b8b-11eb-9298-d2a220e9b866.png)

**Comment by liyangzbx** [comment]
哦哦，在你提交的sm4.py里面有这个函数，但是如果直接pip install gmssl的话，引用的sm4.py源码里就没有去填充的函数。这里有没有办法避开这个问题。因为考虑到移植性，除非每次都把自己定义过的sm4.py文件也拷给别人，否则对方用pip install gmssl的话还是有这个问题。

**Comment by huangbaoliu** [comment]
你把我代码中用到crypt_ecb_nopad的地方改为crypt_ecb吧，配上pip安装的gmssl库应该就没问题了。gmssl库可能只是提供了sm4的ecb与cbc加密，填充这个工作交由应用程序来做了。我这个对sm4.py扩充了ofb与cfb的支持，填充问题，一并由库完成了，其实更好的却是应该将填充由外部负责。
